#!/bin/bash

curl -s "https://aviationweather.gov/api/data/metar?ids=KMCI&format=json&taf=false&hours=12&bbox=40%2C-90%2C45%2C-85" > aviation.json

jq -r '.[].receiptTime' aviation.json | head -n 6

sum=0
cnt=0

for temp in $(jq -r '.[].temp' aviation.json); do
	sum=$(echo "$sum $temp" | awk '{print $1 + $2}')
	cnt=$((cnt + 1))
done

avg=$(echo "$sum $cnt" | awk '{print $1 / $2}')
echo "Average Temperature: $avg"


cld_cnt=0
total=0

for cloud in $(jq -r '.[].clouds[].cover' aviation.json); do
	total=$((total + 1))
	if [[ "$cloud" != "CLR" ]]; then
		cld_cnt=$((cld_cnt + 1))
	fi
done

if ((cld_cnt > total / 2)); then
	echo "Mostly Cloudy: true"
else
	echo "Mostly Cloudy: false"
fi
